### PR TITLE
Fix canvas points on top of footer & on top of legend

### LINKED ISSUE #22: Crop the circles when zoomed in
This is the view on zoom currently

image

Obviously, that cannot be in our final product. We need to either crop the canvas, or somehow filter the dots that get drawn. We could filter them to the specific state you click on, but seeing as hydrology does not obey political boundaries, it would probably be useful to see nearby gage conditions. If we did want to just show the ones for the state someone clicked on then I could add the state code to each points data and filter on that.

### PR DESCRIPTION
**Pull request by lindsaycarr**
Fixes #22. Simple fix to get circles out of footer - had the wrong height for the canvas element so it extended on top of the footer. Added a second svg to the map background called `mapExtras` that contains the legend and site selector point. That way, the map can be behind the canvas points, but the legend and any other svg additions can be on top of the legend points. Also, added white background around the legend so that on zoom, you can still see the legend points. Probably not the long-term fix, but good for MVP.

image

### CODE REVIEW

File: js/app.js [hunk 1]
```diff
@@ -13,34 +13,55 @@ var fig_cfg = {
...
-    .attr("id", "plotarea")
-    .style("z-index", -10)
+    .attr("id", "mapSvg")
     .style("position", "absolute");
 
+// Make a second svg to put the legend and siteHighlighter into
+// This will allow the map to be below the canvas points,
+// But the siteHighlighter and legend to be above the canvas layer
+var svgwidth = d3.select('#mapSvg').attr("width"),
+    svgheight = d3.select('#mapSvg').attr("height");
```
Comment (aappling-usgs) [inline js/app.js]: In the water use vizzy we started moving toward namespacing by using a single global variable to hold all these smaller global variables. Modules are helping with that elsewhere in this code, but consider reworking this file to do the same at some point.

File: js/app.js [hunk 2]
```diff
@@ -13,34 +13,55 @@ var fig_cfg = {
...
-add_color_legend(scale_colors_fxns, legend_cfg);
-add_circle_selector();
-clone_states(fig_cfg);
-clone_legend(fig_cfg, legend_cfg);
-add_placeholder(fig_cfg);
+add_color_legend(scale_colors_fxns, legend_cfg, z_indices);
+add_circle_selector(z_indices);
+clone_states(fig_cfg, z_indices);
+clone_legend(fig_cfg, legend_cfg, z_indices);
+add_placeholder(fig_cfg, z_indices);
```
Comment (aappling-usgs) [inline js/app.js]: I think it could be argued either way, but for the record, I would have used z_indices differently - I would pass z_indices.siteHighlighter to add_circle_selector, pass z_indices.underlayPlaceholder to add_placeholder, etc. rather than needing to know the name of the relevant z index within each of those functions. I think this would help consolidate the need to understand the z_indices structure within this one app.js file rather than causing that info to be distributed across all the modules as well, and that would in turn make the code just a touch more modifiable. But it'd be a minor improvement at best, and I'm not sure if there's a clear-cut best practice in anybody's mind, so just take this as food for thought for future code.

File: js/app.js (hunk 1 above)
Comment (lindsaycarr) [reply js/app.js]: I don't think we can use global variables with this model. We have to pass them into each function. I think I have an idea of how to make this little part better though

File: js/app.js (hunk 2 above)
Comment (lindsaycarr) [reply js/app.js]: Hmm I think that is a good idea - I'm going to go ahead and switch it now since it's not too difficult!
